import {
  Book,
  Clock,
  Droplets,
  Compass,
  BrainCircuit,
  ClipboardCheck,
  Calendar,
  BookOpen,
  Home,
  Settings,
} from "lucide-react";
import type { TopicItem } from "~/types/type";

export const feature = [
  {
    id: "Al-Quran",
    path: "/al-quran",
    label: "Al-Quran",
    icon: Book,
    color: "text-emerald-600",
    bg: "bg-emerald-50",
  },
  {
    id: "Jadwal Sholat",
    path: "/jadwal-sholat",
    label: "Jadwal Sholat",
    icon: Clock,
    color: "text-emerald-600",
    bg: "bg-emerald-50",
  },
  {
    id: "Tasbih",
    path: "/tasbih",
    label: "Tasbih",
    icon: Droplets,
    color: "text-emerald-600",
    bg: "bg-emerald-50",
  },
  {
    id: "Kiblat",
    path: "/kiblat",
    label: "Kiblat",
    icon: Compass,
    color: "text-emerald-600",
    bg: "bg-emerald-50",
  },
  {
    id: "Wirid",
    path: "/wirid",
    label: "Wirid",
    icon: BrainCircuit,
    color: "text-emerald-600",
    bg: "bg-emerald-50",
  },
  {
    id: "Ibadah",
    path: "/ibadah",
    label: "Ibadah Tracker",
    icon: ClipboardCheck,
    color: "text-emerald-600",
    bg: "bg-emerald-50",
  },
  {
    id: "Kalender",
    path: "/kalender",
    label: "Kalender",
    icon: Calendar,
    color: "text-emerald-600",
    bg: "bg-emerald-50",
  },
  {
    id: "Yasin & Tahlil",
    path: "/yasin-tahlil",
    label: "Yasin & Tahlil",
    icon: BookOpen,
    color: "text-emerald-600",
    bg: "bg-emerald-50",
  },
];

export const STATIC_HIKMAH = [
  {
    text: "Allah tidak membebani seseorang melainkan sesuai dengan kesanggupannya.",
    source: "QS. Al-Baqarah: 286",
  },
  {
    text: "Sesungguhnya sesudah kesulitan itu ada kemudahan.",
    source: "QS. Al-Insyirah: 6",
  },
  {
    text: "Jadikanlah sabar dan shalat sebagai penolongmu.",
    source: "QS. Al-Baqarah: 45",
  },
  {
    text: "Barangsiapa yang bertaqwa kepada Allah, niscaya Dia akan mengadakan baginya jalan keluar.",
    source: "QS. At-Talaq: 2",
  },
  {
    text: "Hati yang bersyukur adalah magnet bagi keajaiban.",
    source: "Hikmah Sabda",
  },
];

export const topics: TopicItem[] = [
  {
    id: "1",
    title: "Kumpulan Khutbah Bulan Sya'ban",
    imageUrl: "https://picsum.photos/seed/topic1/300/200",
  },
  {
    id: "2",
    title: "Amalan Malam Nisfu Sya'ban",
    imageUrl: "https://picsum.photos/seed/topic2/300/200",
  },
  {
    id: "3",
    title: "Persiapan Menyambut Ramadhan",
    imageUrl: "https://picsum.photos/seed/topic3/300/200",
  },
];

export const recommendations: TopicItem[] = [
  {
    id: "1",
    title: "Doa Malam Nisfu Sya'ban",
    imageUrl: "https://picsum.photos/seed/rec1/300/200",
  },
  {
    id: "2",
    title: "Dzikir Penenang Hati",
    imageUrl: "https://picsum.photos/seed/rec2/300/200",
  },
  {
    id: "3",
    title: "Kisah Sahabat Nabi",
    imageUrl: "https://picsum.photos/seed/rec3/300/200",
  },
];

export const tabs = [
  { id: "Beranda", path: "/", icon: Home, label: "Beranda" },
  { id: "Al-Quran", path: "/al-quran", icon: BookOpen, label: "Al-Quran" },
  {
    id: "Ibadah",
    path: "/ibadah",
    icon: ClipboardCheck,
    label: "Ibadah",
  },
  { id: "Kalender", path: "/kalender", icon: Calendar, label: "Kalender" },
  {
    id: "Pengaturan",
    path: "/pengaturan",
    icon: Settings,
    label: "Pengaturan",
  },
];

export const idTranslations: Record<number, string> = {
  1: "Pembukaan",
  2: "Sapi Betina",
  3: "Keluarga Imran",
  4: "Wanita",
  5: "Hidangan",
  6: "Binatang Ternak",
  7: "Tempat yang Tinggi",
  8: "Rampasan Perang",
  9: "Pengampunan",
  10: "Yunus",
  11: "Hud",
  12: "Yusuf",
  13: "Guruh",
  14: "Ibrahim",
  15: "Al-Hijr",
  16: "Lebah",
  17: "Perjalanan Malam",
  18: "Penghuni Gua",
  19: "Maryam",
  20: "Thaha",
  21: "Para Nabi",
  22: "Haji",
  23: "Orang-orang Beriman",
  24: "Cahaya",
  25: "Pembeda",
  26: "Para Penyair",
  27: "Semut",
  28: "Kisah-kisah",
  29: "Laba-laba",
  30: "Bangsa Romawi",
  31: "Luqman",
  32: "Sajdah",
  33: "Golongan yang Bersekutu",
  34: "Saba'",
  35: "Pencipta",
  36: "Yasin",
  37: "Barisan-barisan",
  38: "Shad",
  39: "Rombongan-rombongan",
  40: "Maha Pengampun",
  41: "Yang Dijelaskan",
  42: "Musyawarah",
  43: "Perhiasan",
  44: "Kabut",
  45: "Yang Bertekuk Lutut",
  46: "Bukit-bukit Pasir",
  47: "Muhammad",
  48: "Kemenangan",
  49: "Kamar-kamar",
  50: "Qaf",
  51: "Angin yang Menerbangkan",
  52: "Bukit",
  53: "Bintang",
  54: "Bulan",
  55: "Yang Maha Pemurah",
  56: "Hari Kiamat",
  57: "Besi",
  58: "Wanita yang Mengajukan Gugatan",
  59: "Pengusiran",
  60: "Wanita yang Diuji",
  61: "Barisan",
  62: "Hari Jum'at",
  63: "Orang-orang Munafik",
  64: "Hari Dinampakkan Kesalahan",
  65: "Talak",
  66: "Mengharamkan",
  67: "Kerajaan",
  68: "Pena",
  69: "Hari Kiamat (Pasti)",
  70: "Tempat Naik",
  71: "Nuh",
  72: "Jin",
  73: "Orang yang Berselimut",
  74: "Orang yang Berkumul",
  75: "Hari Kiamat",
  76: "Manusia",
  77: "Malaikat-malaikat yang Diutus",
  78: "Berita Besar",
  79: "Malaikat yang Mencabut",
  80: "Ia Bermuka Masam",
  81: "Pengulungan",
  82: "Terbelah",
  83: "Orang-orang yang Curang",
  84: "Terbelah",
  85: "Gugusan Bintang",
  86: "Yang Datang di Malam Hari",
  87: "Yang Maha Tinggi",
  88: "Hari Pembalasan",
  89: "Fajar",
  90: "Negeri",
  91: "Matahari",
  92: "Malam",
  93: "Waktu Dhuha",
  94: "Kelapangan",
  95: "Buah Tin",
  96: "Segumpal Darah",
  97: "Kemuliaan",
  98: "Bukti Nyata",
  99: "Kegoncangan",
  100: "Kuda Perang yang Berlari Kencang",
  101: "Hari Kiamat",
  102: "Bermegah-megahan",
  103: "Masa",
  104: "Pengumpat",
  105: "Gajah",
  106: "Suku Quraisy",
  107: "Barang yang Berguna",
  108: "Nikmat yang Banyak",
  109: "Orang-orang Kafir",
  110: "Pertolongan",
  111: "Gejolak Api",
  112: "Ikhlas",
  113: "Waktu Subuh",
  114: "Manusia",
};

export const JUZ_MAPPING: Record<number, string> = {
  1: "Al-Fatihah: 1 - Al-Baqarah: 141",
  2: "Al-Baqarah: 142 - Al-Baqarah: 252",
  3: "Al-Baqarah: 253 - Ali 'Imran: 92",
  4: "Ali 'Imran: 93 - An-Nisa': 23",
  5: "An-Nisa': 24 - An-Nisa': 147",
  6: "An-Nisa': 148 - Al-Ma'idah: 81",
  7: "Al-Ma'idah: 82 - Al-An'am: 110",
  8: "Al-An'am: 111 - Al-A'raf: 87",
  9: "Al-A'raf: 88 - Al-Anfal: 40",
  10: "Al-Anfal: 41 - At-Tawbah: 92",
  11: "At-Tawbah: 93 - Hud: 5",
  12: "Hud: 6 - Yusuf: 52",
  13: "Yusuf: 53 - Ibrahim: 52",
  14: "Al-Hijr: 1 - An-Nahl: 128",
  15: "Al-Isra': 1 - Al-Kahf: 74",
  16: "Al-Kahf: 75 - Ta-Ha: 135",
  17: "Al-Anbiya': 1 - Al-Hajj: 78",
  18: "Al-Mu'minun: 1 - Al-Furqan: 20",
  19: "Al-Furqan: 21 - An-Naml: 55",
  20: "An-Naml: 56 - Al-'Ankabut: 45",
  21: "Al-'Ankabut: 46 - Al-Ahzab: 30",
  22: "Al-Ahzab: 31 - Ya-Sin: 27",
  23: "Ya-Sin: 28 - Az-Zumar: 31",
  24: "Az-Zumar: 32 - Fussilat: 46",
  25: "Fussilat: 47 - Al-Jathiyah: 37",
  26: "Al-Ahqaf: 1 - Az-Zariyat: 30",
  27: "Az-Zariyat: 31 - Al-Hadid: 29",
  28: "Al-Mujadilah: 1 - At-Tahrim: 12",
  29: "Al-Mulk: 1 - Al-Mursalat: 50",
  30: "An-Naba': 1 - An-Nas: 6",
};
