import {
  Book,
  Clock,
  Droplets,
  Compass,
  BrainCircuit,
  ClipboardCheck,
  Calendar,
  BookOpen,
} from "lucide-react";

export const feature = [
  {
    id: "Al-Quran",
    path: "/al-quran",
    label: "Al-Quran",
    icon: Book,
    color: "text-emerald-600",
    bg: "bg-emerald-50",
  },
  {
    id: "Jadwal Sholat",
    path: "/jadwal-sholat",
    label: "Jadwal Sholat",
    icon: Clock,
    color: "text-emerald-600",
    bg: "bg-emerald-50",
  },
  {
    id: "Tasbih",
    path: "/tasbih",
    label: "Tasbih",
    icon: Droplets,
    color: "text-emerald-600",
    bg: "bg-emerald-50",
  },
  {
    id: "Kiblat",
    path: "/kiblat",
    label: "Kiblat",
    icon: Compass,
    color: "text-emerald-600",
    bg: "bg-emerald-50",
  },
  {
    id: "Wirid",
    path: "/wirid",
    label: "Wirid",
    icon: BrainCircuit,
    color: "text-emerald-600",
    bg: "bg-emerald-50",
  },
  {
    id: "Ibadah",
    path: "/ibadah",
    label: "Ibadah",
    icon: ClipboardCheck,
    color: "text-emerald-600",
    bg: "bg-emerald-50",
  },
  {
    id: "Kalender",
    path: "/kalender",
    label: "Kalender",
    icon: Calendar,
    color: "text-emerald-600",
    bg: "bg-emerald-50",
  },
  {
    id: "Yasin & Tahlil",
    path: "/yasin-tahlil",
    label: "Yasin & Tahlil",
    icon: BookOpen,
    color: "text-emerald-600",
    bg: "bg-emerald-50",
  },
];
